urg_node2:
  ros__parameters:
    ip_address: '192.168.1.11'
    ip_port: 10940
    frame_id : 'laser_rear'
    calibrate_time : true
    synchronize_time : true
    publish_intensity : true
    publish_multiecho : false
    error_limit : 4
    error_reset_period : 5.0
    diagnostics_tolerance : 0.05
    diagnostics_window_time : 5.0
    time_offset : 0.0
    angle_min : -2.0
    angle_max : 2.0
    skip : 0
    cluster : 1
